import { sendPush } from '../utils/apn.js';
import { Router } from 'express';
import multer from 'multer';
import { v4 as uuidv4 } from 'uuid';
import { supabase } from '../utils/supabase.js';
import nodemailer from 'nodemailer';

const router = Router();

router.post('/send-invite', async (req, res) => {
  const { to, name, businessName, link, referenceCode, imageUrl } = req.body;

  if (!to || !name || !businessName || !link) {
    return res.status(400).json({ error: 'Missing required fields.' });
  }

  console.log('to: ', to);
  console.log('name: ', name);
  console.log('businessName: ', businessName);
  console.log('link: ', link);
  console.log('imageUrl: ', imageUrl);

  try {
    const transporter = nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: process.env.GMAIL_USERNAME,
        pass: process.env.GMAIL_PASSWORD,
      },
    });

    const htmlContent = `
      <div style="font-family: sans-serif; padding: 20px;">
        <h2>Hi ${name},</h2>
        <p>You’ve been invited to join <strong>${businessName}</strong> on Movaro!</p>
        <p>Please click the button below to download the app and complete your signup:</p>
        <a href="${link}" style="background-color: #1D4ED8; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Download Movaro</a>
        <br /><br />
        ${referenceCode ? `<p>Invitation Code: ${referenceCode}</p>` : ''}
        <p>Use the invitation code to sign up in the app.</p>
        <br /><br />
        ${imageUrl ? `<img src="${imageUrl}" alt="Movaro" style="margin-top: 20px; max-width: 100%; height: auto;" />` : ''}
        <p style="margin-top: 20px;">If you have any questions, contact your manager or support@movaro.app.</p>
      </div>
    `;

    await transporter.sendMail({
      from: process.env.GMAIL_USERNAME,
      to,
      subject: `You're Invited to Join ${businessName} on Movaro`,
      html: htmlContent,
    });

    res.status(200).json({ success: true });
  } catch (error) {
    console.error('Error sending invite email:', error);
    res.status(500).json({ error: 'Failed to send email.' });
  }
});

router.post('/send-custom-plan', async (req, res) => {
  const { to, name, businessName, username, userid, businessId, drivers, stops } = req.body;

  if (!to || !name || !businessName || !username || !userid || !businessId || !drivers || !stops) {
    return res.status(400).json({ error: 'Missing required fields.' });
  }

  console.log('Custom plan request received:', {
    to, name, businessName, username, userid, businessId, drivers, stops
  });

  try {
    const transporter = nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: process.env.GMAIL_USERNAME,
        pass: process.env.GMAIL_PASSWORD,
      },
    });

    const htmlContent = `
      <div style="font-family: sans-serif; padding: 20px;">
        <h2>📩 New Custom Plan Request</h2>
        <p>A user has requested a custom Movaro business subscription plan.</p>
        
        <h3>Business Information</h3>
        <ul>
          <li><strong>Business Name:</strong> ${businessName}</li>
          <li><strong>Business ID:</strong> ${businessId}</li>
        </ul>

        <h3>User Information</h3>
        <ul>
          <li><strong>Name:</strong> ${name}</li>
          <li><strong>Username:</strong> ${username}</li>
          <li><strong>User ID:</strong> ${userid}</li>
        </ul>

        <h3>Requested Plan Details</h3>
        <ul>
          <li><strong>Number of Drivers:</strong> ${drivers}</li>
          <li><strong>Monthly Stops:</strong> ${stops}</li>
        </ul>

        <p style="margin-top: 20px;">
          Please follow up with <strong>${name}</strong> at <strong>${businessName}</strong> to discuss a custom plan.
        </p>

        <p style="margin-top: 20px; font-size: 12px; color: #888;">
          This email was automatically generated by Movaro.
        </p>
      </div>
    `;

    await transporter.sendMail({
      from: to,
      to: process.env.GMAIL_USERNAME,
      subject: `New Custom Plan Request from ${businessName}`,
      html: htmlContent,
    });

    res.status(200).json({ success: true });
  } catch (error) {
    console.error('Error sending custom plan email:', error);
    res.status(500).json({ error: 'Failed to send custom plan email.' });
  }
});

// POST /send-bulk-message
// Purpose: Notify Movaro team (and business) that a user is requesting a bulk upload
// Notes:
// - Uses Gmail SMTP (recommend an App Password)
// - Sends both HTML and text versions
// - Sets replyTo to the user's email so you can reply directly

router.post('/send-bulk-message', async (req, res) => {
  const {
    user_id,
    username,
    first_name,
    last_name,
    user_email,
    business_id,
    business_name,
    business_email,
    business_address,
    phone,
    role,
    plan,
    customer_count,
    vendor_count,
    expected_file_format,
    notes,
    type
  } = req.body;

  try {
    const missing = [];
    if (!user_id) missing.push('user_id');
    if (!first_name) missing.push('first_name');
    if (!last_name) missing.push('last_name');
    if (!user_email) missing.push('user_email');
    if (!business_id) missing.push('business_id');
    if (!business_name) missing.push('business_name');

    if (missing.length) {
      console.log('missing: ', missing);
      return res.status(400).json({ error: `Missing required fields: ${missing.join(', ')}` });
    }

    const transporter = nodemailer.createTransport({
      service: 'Gmail',
      auth: {
        user: process.env.GMAIL_USERNAME,
        pass: process.env.GMAIL_PASSWORD,
      },
    });

    const subject = `Bulk Upload (${type}) – ${business_name} (${first_name} ${last_name})`;

    const htmlContent = `
      <div style="font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Inter,Arial; padding:20px; line-height:1.5;">
        <h2 style="margin:0 0 12px;">Bulk Upload Request (${type})</h2>
        <p style="margin:0 0 16px;">A Movaro user has requested a <strong>bulk upload of customers and vendors</strong>.</p>

        <h3 style="margin:16px 0 8px;">User Details</h3>
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
          <tr><td style="padding:4px 8px;"><strong>User ID</strong></td><td style="padding:4px 8px;">${user_id}</td></tr>
          ${username ? `<tr><td style="padding:4px 8px;"><strong>Username</strong></td><td style="padding:4px 8px;">${username}</td></tr>` : ''}
          <tr><td style="padding:4px 8px;"><strong>Name</strong></td><td style="padding:4px 8px;">${first_name} ${last_name}</td></tr>
          <tr><td style="padding:4px 8px;"><strong>Email</strong></td><td style="padding:4px 8px;">${user_email}</td></tr>
          ${phone ? `<tr><td style="padding:4px 8px;"><strong>Phone</strong></td><td style="padding:4px 8px;">${phone}</td></tr>` : ''}
          ${role ? `<tr><td style="padding:4px 8px;"><strong>Role</strong></td><td style="padding:4px 8px;">${role}</td></tr>` : ''}
        </table>

        <h3 style="margin:16px 0 8px;">Business Details</h3>
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
          <tr><td style="padding:4px 8px;"><strong>Business ID</strong></td><td style="padding:4px 8px;">${business_id}</td></tr>
          <tr><td style="padding:4px 8px;"><strong>Business Name</strong></td><td style="padding:4px 8px;">${business_name}</td></tr>
          <tr><td style="padding:4px 8px;"><strong>Business Email</strong></td><td style="padding:4px 8px;">${business_email}</td></tr>
          ${business_address ? `<tr><td style="padding:4px 8px;"><strong>Business Address</strong></td><td style="padding:4px 8px;">${business_address}</td></tr>` : ''}
          ${plan ? `<tr><td style="padding:4px 8px;"><strong>Plan</strong></td><td style="padding:4px 8px;">${plan}</td></tr>` : ''}
        </table>

        <h3 style="margin:16px 0 8px;">Bulk Upload Context</h3>
        <table cellspacing="0" cellpadding="0" style="border-collapse:collapse;">
          ${Number.isFinite(customer_count) ? `<tr><td style="padding:4px 8px;"><strong>Estimated Customers</strong></td><td style="padding:4px 8px;">${customer_count}</td></tr>` : ''}
          ${Number.isFinite(vendor_count) ? `<tr><td style="padding:4px 8px;"><strong>Estimated Vendors</strong></td><td style="padding:4px 8px;">${vendor_count}</td></tr>` : ''}
          ${expected_file_format ? `<tr><td style="padding:4px 8px;"><strong>Expected File Format</strong></td><td style="padding:4px 8px;">${expected_file_format}</td></tr>` : ''}
        </table>

        ${notes ? `<p style="margin:16px 0;"><strong>User Notes:</strong><br>${notes.replace(/\n/g,'<br>')}</p>` : ''}

        <p style="margin-top:16px; color:#111;">Please reply directly to <a href="mailto:${user_email}">${user_email}</a> with instructions. (We target a 1 business day response.)</p>

        <hr style="margin:20px 0; border:none; border-top:1px solid #e5e7eb;" />
        <p style="font-size:12px; color:#6b7280;">This notification was generated by Movaro.</p>
      </div>
    `;

    const textContent = `
Bulk Upload Request

A Movaro user has requested a bulk upload of customers and vendors.

User Details
- User ID: ${user_id}
${username ? `- Username: ${username}` : ''}
- Name: ${first_name} ${last_name}
- Email: ${user_email}
${phone ? `- Phone: ${phone}` : ''}
${role ? `- Role: ${role}` : ''}

Business Details
- Business ID: ${business_id}
- Business Name: ${business_name}
- Business Email: ${business_email}
${business_address ? `- Business Address: ${business_address}` : ''}
${plan ? `- Plan: ${plan}` : ''}

Bulk Upload Context
${Number.isFinite(customer_count) ? `- Estimated Customers: ${customer_count}` : ''}
${Number.isFinite(vendor_count) ? `- Estimated Vendors: ${vendor_count}` : ''}
${expected_file_format ? `- Expected File Format: ${expected_file_format}` : ''}

${notes ? `User Notes:\n${notes}\n` : ''}

Please reply to ${user_email} with instructions (target: 1 business day).
    `.trim();

    // You can route to internal ops, the business, or both.
    const internalOps = process.env.OPERATIONS_EMAIL || 'ops@movaro.app';

    await transporter.sendMail({
      from: business_email,
      to: process.env.GMAIL_USERNAME,
      cc: internalOps,
      subject,
      html: htmlContent,
      text: textContent,
      replyTo: user_email,
      headers: {
        'X-Movaro-Notification': 'BulkUploadRequest',
        'X-Movaro-Business-ID': String(business_id),
        'X-Movaro-User-ID': String(user_id),
      },
    });

    return res.status(200).json({ success: true });
  } catch (err) {
    console.error('Error sending bulk upload email:', err);
    return res.status(500).json({ error: 'Failed to send email.' });
  }
});


// Trigger push
router.post('/send', async (req, res) => {
  const { token, title, body, sendAt } = req.body;
  if (sendAt) {
    setTimeout(async () => {
      try {
        const result = await sendPush(token, title, body);
        console.log('📤 Scheduled APNs result:', JSON.stringify(result, null, 2));
      } catch (err) {
        console.error('❌ Scheduled push error:', err);
      }
    }, sendAt);

    console.log(`⏳ Notification scheduled in ${sendAt / 60000} seconds`);

    return res.status(200).json({ success: true, scheduled: true, delayInMs: sendAt });
  } else {
    try {
      const result = await sendPush(token, title, body);
      console.log('📤 APNs result:', JSON.stringify(result, null, 2));
      return res.status(200).json({ success: true });
    } catch (err) {
      console.error('❌ Push route error:', err);
      return res.status(500).json({ error: 'Internal server error' });
    }
  }
});

const upload = multer({ storage: multer.memoryStorage() });

router.post('/upload-profile-image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided.' });
    }

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname;
    const uniqueName = `${uuidv4()}_${originalName}`;

    const { data, error } = await supabase.storage
      .from('profile-images')
      .upload(uniqueName, fileBuffer, {
        contentType: req.file.mimetype,
      });

    if (error) {
      console.error('Supabase upload error:', error);
      return res.status(500).json({ error: 'Failed to upload to storage' });
    }

    const publicUrl = `https://bsatjkrkstfwcmvsjzqp.supabase.co/storage/v1/object/public/profile-images/${uniqueName}`;

    return res.status(200).json({ success: true, url: publicUrl });
  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/upload-product-image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided.' });
    }

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname;
    const uniqueName = `${uuidv4()}_${originalName}`;

    const { data, error } = await supabase.storage
      .from('product-images')
      .upload(uniqueName, fileBuffer, {
        contentType: req.file.mimetype,
      });

    if (error) {
      console.error('Supabase upload error:', error);
      return res.status(500).json({ error: 'Failed to upload to storage' });
    }

    const publicUrl = `https://bsatjkrkstfwcmvsjzqp.supabase.co/storage/v1/object/public/product-images/${uniqueName}`;

    return res.status(200).json({ success: true, url: publicUrl });
  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/upload-payment-image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided.' });
    }

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname;
    const uniqueName = `${uuidv4()}_${originalName}`;

    const { data, error } = await supabase.storage
      .from('payment-images')
      .upload(uniqueName, fileBuffer, {
        contentType: req.file.mimetype,
      });

    if (error) {
      console.error('Supabase upload error:', error);
      return res.status(500).json({ error: 'Failed to upload to storage' });
    }

    const publicUrl = `https://bsatjkrkstfwcmvsjzqp.supabase.co/storage/v1/object/public/payment-images/${uniqueName}`;

    return res.status(200).json({ success: true, url: publicUrl });
  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/upload-pickup-admin-image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided.' });
    }

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname;
    const uniqueName = `${uuidv4()}_${originalName}`;

    const { data, error } = await supabase.storage
      .from('pickup-admin-images')
      .upload(uniqueName, fileBuffer, {
        contentType: req.file.mimetype,
      });

    if (error) {
      console.error('Supabase upload error:', error);
      return res.status(500).json({ error: 'Failed to upload to storage' });
    }

    const publicUrl = `https://bsatjkrkstfwcmvsjzqp.supabase.co/storage/v1/object/public/pickup-admin-images/${uniqueName}`;

    return res.status(200).json({ success: true, url: publicUrl });
  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/upload-pickup-image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided.' });
    }

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname;
    const uniqueName = `${uuidv4()}_${originalName}`;

    const { data, error } = await supabase.storage
      .from('pickup-images')
      .upload(uniqueName, fileBuffer, {
        contentType: req.file.mimetype,
      });

    if (error) {
      console.error('Supabase upload error:', error);
      return res.status(500).json({ error: 'Failed to upload to storage' });
    }

    const publicUrl = `https://bsatjkrkstfwcmvsjzqp.supabase.co/storage/v1/object/public/pickup-images/${uniqueName}`;

    return res.status(200).json({ success: true, url: publicUrl });
  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

router.post('/upload-driver-image', upload.single('file'), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided.' });
    }

    const fileBuffer = req.file.buffer;
    const originalName = req.file.originalname;
    const uniqueName = `${uuidv4()}_${originalName}`;

    const { data, error } = await supabase.storage
      .from('driver-images')
      .upload(uniqueName, fileBuffer, {
        contentType: req.file.mimetype,
      });

    if (error) {
      console.error('Supabase upload error:', error);
      return res.status(500).json({ error: 'Failed to upload to storage' });
    }

    const publicUrl = `https://bsatjkrkstfwcmvsjzqp.supabase.co/storage/v1/object/public/driver-images/${uniqueName}`;

    return res.status(200).json({ success: true, url: publicUrl });
  } catch (error) {
    console.error('Server error:', error);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

export default router;
